from generators.CSRFPayloadGenerator import CSRFPayloadGenerator

class POCGenerationService():
	

	def __init__(self,payloads):
		self.payloads=payloads

	def csrf_poc(self,url):
		poc_gen = CSRFPayloadGenerator()
		poc = ""
		poc += "<html>\n"
		poc += "<!-- CSRF PoC - Generated by SPUTR -->\n"
  		poc += "<body>"
  		poc += "<script>history.pushState('', '', '/')</script>\n"
  		poc += "<form action="+url+" method=\"POST\">\n"
  		#iterate over inputs
  		for param in self.payloads:
  			poc += poc_gen.create_payload(param,self.payloads[param])
  		poc += "<input type=\"submit\" value=\"Submit request\" />\n"
  		poc += "</form>\n"
  		poc += "</body>\n"
		poc += "</html>\n"
  		return poc


  	def writeToFile(self,poc):
  		target_poc = open("CSRF_PoC.html", 'w')
  		target_poc.write(poc)
  		target.close()

